### ISSUE TITLE
Part number for the USB-C connector and crystal

### ISSUE THREAD

**Issue by liudr** [geraicerdas/ESP32-Cam-Programmer#2]
Hi,
Thanks for the design always! Is it possible to share the part number for the USB-C connector and the crystal?
I've run into issues with mismatched crystals in the past so I would appreciate a part number for that. Thanks again!

**Comment by geraicerdas** [comment]
I use U262-161N-4BVC11 for USB type C connector. It has 16 pin SMD
And for 12Mhz Crystal : 72012000RW1

**Comment by liudr** [comment]
Great! Thanks much!
