### ISSUE TITLE
automatic reset by software not working (hard resetting via rts pin)

### ISSUE THREAD

**Issue by linsThankachan** [geraicerdas/ESP32-Cam-Programmer#3]
hello, 
i'm using an esp32 cam and i have used your circuit to realise automatic code upload. Firstly thank u for that . there is a problem in my final board the automatic reset that is given by arduino software (hardresetting via rts pin) is not working.
can you tell me why?
[Schematic_esp32_cam_board_2021-09-25.pdf](https://github.com/geraicerdas/ESP32-Cam-Programmer/files/7230161/Schematic_esp32_cam_board_2021-09-25.pdf)

**Comment by geraicerdas** [comment]
Hi, Have you tried to assemble and test the ESP32 and the auto-program circuit only?

**Comment by linsThankachan** [comment]
now it is working perfectly.
connecting anything to the straping pins will result in reset not working. in my case GPIO13 . I have another doubt why is that c2 capacitor which is connected to EN used. is it used for debounce of the EN switch? and do we need the 10K pullup resistor(R6) because GPIO0 is already pulled up internally when GND is not applied to it.

**Comment by geraicerdas** [comment]
Thank for the updates. C2 with the specific value from 1-10nF is the important thing. It not used for debouncing EN button only, but it allow EN to be slow to rise while IO0 falls low. This state will giving the opportunity of correct timing (rise-fall) for ESP32 so it can enter the programming mode. And yes, for the R6 connected to BOOT button as mentioned in the legend of schematic, that parts might be not necessary as your thought.

**Comment by linsThankachan** [comment]
so C2 is in nF range not in uF. typed wrongly?
In the schematic it is 10uF.
i have done without capacitor(10uF) also and it is working.

**Comment by geraicerdas** [comment]
Sorry. 1-10uF. I've tried a large numbers of ESP32, without this cap, I only success with a few board. This cap help all boards can be done without any issues.

**Comment by linsThankachan** [comment]
OK thank you for your help.
Closing the issue
